name: flutter_keyboard_visibility_temp_fork
description: Temporary fork of flutter_keyboard_visibility plugin to address some issues
version: 0.1.1
homepage: https://github.com/EchoEllet/flutter_keyboard_visibility_temp_fork
repository: https://github.com/EchoEllet/flutter_keyboard_visibility_temp_fork

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  meta: ">=1.0.0 <2.0.0"
  flutter_keyboard_visibility_platform_interface: ^2.0.0
  flutter_keyboard_visibility_linux: ^1.0.0
  flutter_keyboard_visibility_macos: ^1.0.0
  flutter_keyboard_visibility_windows: ^1.0.0
  flutter:
    sdk: flutter
  # For web only
  web: ^1.0.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  mockito: ^5.0.17
  pedantic: ^1.11.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jrai.flutter_keyboard_visibility
        pluginClass: FlutterKeyboardVisibilityPlugin
      ios:
        pluginClass: FlutterKeyboardVisibilityPlugin
      web:
        pluginClass: FlutterKeyboardVisibilityPluginWeb
        fileName: flutter_keyboard_visibility_web.dart
      macos:
        default_package: flutter_keyboard_visibility_macos
      linux:
        default_package: flutter_keyboard_visibility_linux
      windows:
        default_package: flutter_keyboard_visibility_windows