name: flutter_keyboard_visibility_example
description: Demonstrates how to use the flutter_keyboard_visibility plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_keyboard_visibility_temp_fork:
    path: ../

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true